

spring.datasource.url= jdbc:mysql://localhost:3306/Springboot_jpa_mapping
spring.datasource.username= root
spring.datasource.password= root
spring.jpa.show-sql=true


 spring.jpa.hibernate.ddl-auto=update



# spring.jpa.hibernate.ddl-auto=create tells Hibernate to create the database tables from your JPA entity classes when the application starts.
# spring.jpa.hibernate.ddl-auto=update tells Hibernate to update the existing database tables according to your JPA entity classes when the application starts, without deleting the existing data.


# create :
#create
#   ?
#Application starts
#   ?
#Hibernate creates the table again
#   ?
#Old table/data can be removed


# update :
#update
#   ?
#Application starts
#   ?
#Existing table is kept
#   ?
#Existing data is kept
#   ?
#New save() adds new rows
